
  #################################    测试环境配置   #################################

# Tomcat
server:
  uri-encoding: UTF-8
  max-threads: 1000
  min-spare-threads: 30
  port: 8888
# mysql
spring:
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, classpath:/public/
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/facerecongnition?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
    mvc:
        view:
            prefix: /pages/
        static-path-pattern: /static/**
qiniu:
  accessKey: J04pG4Y6jI6-PhGoqjOMXCUqVMhOdrCBJgEPfMpi
  secretKey: BotxLJCoZtLd89AceJl1nFxw7xEhOLnX20kVIO1W
  #domain: http://xcx.vinda.com/Fg58mXa91qLnYr5VVoW9IpV_L2QX
  domain: pq9d2dt13.bkt.clouddn.com
  #cdn: xcx.vinda.com/ #下面bucket绑定的cdn 域名
  bucket: facePlus
  zone: zone2
#mybatis
mybatis:
  mapper-locations: classpath:/mappers/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
  #实体扫描，多个package用逗号或者分号分隔
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml 
  #实体扫描，多个package用逗号或者分号分隔
  #type-aliases-package:  cn.jeeweb.web.modules.*.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 配置slq打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    dbType: mysql #设置全局属性用于控制数据库的类型
 # slf4j日志配置
logging:
     # 配置级别
     level:
     #分包配置级别，即不同的目录下可以使用不同的级别
        com.yida: trace
     # 指定输出日志的文件名，默认输出至当前项目目录下
     file: log/yida.log   
    